### ISSUE TITLE
Add new plugin on WebVim

### ISSUE THREAD

**Issue by kqesar** [krampstudio/webvim#22]
Hello,
Congrats for job with your Vim's for Web Developpement.
I want use VIM for Symfony Project and i wish to install few plugins for support twig and symfony but i can't :/

Have you a process for install plugins manually ?
Thank you for advance.
Best Regards,

**Comment by krampstudio** [comment]
You need to add a line to the `plugins/def.vim` with the needed plugins. For example, if you'd like to add https://github.com/evidens/vim-twig, add the line : 
```viml
 Plug "evidens/vim-twig"
```
reload and open vim an run `:PlugInstall`

**Comment by kqesar** [comment]
Thank for your fast answer, it's work !
