### ISSUE TITLE
Checking if node is executable

### ISSUE THREAD

**Issue by conbrad** [krampstudio/webvim#28]
The vimrc file checks if it can execute node js on line 42:

`if !executable('node') || !executable('npm')`

node is executed by issuing `nodejs` by default though, the check should be

`if !executable('nodejs') || !executable('npm')`

**Comment by krampstudio** [comment]
On which OS ? How did you install node ? I think it depends on the way you've installed it : 
 - using [nvm](https://github.com/creationix/nvm) or from the [sources](https://nodejs.org/en/download/current/) you'll have only the node binary
 - using the debian's [nodejs](https://packages.debian.org/jessie/nodejs) package you'll get the nodejs binary in addition to node
 - using  the [nodesource](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions) repo I think there's only the node binary

Is it a problem ? If yes I can check for at least one.

**Comment by conbrad** [comment]
It's not a huge issue, but for an extra check will cause less friction for new users.
